### ISSUE TITLE
Jenkins asks for a login

### ISSUE THREAD

**Issue by anderl80** [ewolff/user-registration#7]
After vagrant up and connecting to the Jenkins server, a login page appears. The book or the code says nothing about the login.

**Comment by ewolff** [comment]
I suspect there is a problem with the installation. I ran it and got log entries like this:

> ==> default: Warning: /Stage[main]/Main/Jenkins::Plugin[build-pipeline-plugin]/File[/var/lib/jenkins/plugins/build-pipeline-plugin.hpi.disabled]: Skipping because of failed dependencies
> ==> default: Error: Execution of '/usr/bin/curl https://updates.jenkins-ci.org/latest/credentials.hpi -o /tmp/credentials.hpi_20161102-9810-q72602 -fsSL --max-redirs 5' returned 56: curl: (56) Recv failure: Connection reset by peer
> ==> default: 
> ==> default: Error: /Stage[main]/Jenkins::Config/Jenkins::Plugin[credentials]/Archive[credentials.hpi]/ensure: change from absent to present failed: Execution of '/usr/bin/curl https://updates.jenkins-ci.org/latest/credentials.hpi -o /tmp/credentials.hpi_20161102-9810-q72602 -fsSL --max-redirs 5' returned 56: curl: (56) Recv failure: Connection reset by peer

At the end:

> The SSH command responded with a non-zero exit status. Vagrant
> assumes that this means the command failed. The output for this command
> should be in the log above. Please read the output to determine what
> went wrong.

Is this also the case for you or did the installation succeed? Also @spanneberg should take a look...

**Comment by spanneberg** [comment]
Plz try the updated version (https://github.com/ewolff/user-registration-V2). Also see https://github.com/ewolff/user-registration-V2/blob/master/ci-setup/README.md for the login. Jenkins is now secured by default and requires an initial admin login for further configuration.

**Comment by ewolff** [comment]
@spanneberg Thanks. However, the problem I described is actually in the current version. Can you check?

**Comment by anderl80** [comment]
Brilliant! Thank you!! You might specify to login with user "Admin", took me some minutes to find out.
